site_name: LayerForge
theme:
  name: material
  logo: assets/layerforge_logo_nbg.png # for on website
  favicon: assets/layerforge_logo_nbg.png # in search bar

markdown_extensions:
  - attr_list
  - md_in_html
  - tables